messages:
  start: 'Привет, этот бот создан, чтобы делиться с тобой 1 полезной статьей в день. Я сам лично отбираю каждую статью/ видео, которую можно внедрить в свою повседневную жизнь или работу. Я убежден, что важно уметь работать с новыми технологиями☺️. Поверь - это не так сложно, а жизнь упрощает сильно. Все что тебе будет приходить - это материал, который я внедряю к себе и своей команде.
Подписывайся на наш канал, если хочешь глубже погрузиться в тему и поддержать меня): <a href="https://t.me/WebSindicat">WebSindicat<a/>'
keyboard:
  add_profile: "Добавить профиль"
  edit_profile: "Редактировать профиль"
